services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: log-analysis-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - log-analysis-network

  app:
    build: .
    container_name: log-analysis-app
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET}
      - GENAPI_KEY=${GENAPI_KEY}
      - GENAPI_URL=${GENAPI_URL}
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      - elasticsearch
    networks:
      - log-analysis-network

volumes:
  elasticsearch_data:

networks:
  log-analysis-network:
    driver: bridge
